// Fonte única de logos de clientes da OxBrand.
// Usada pela grade (/nossos-clientes, máscara preta) e pelo carrossel (cor original).
// Para atualizar os logos em todo o site, edite APENAS esta lista.

export const CLIENT_LOGOS = [
  { src: '/images/wp/clients/aero-brasil.webp', alt: 'Aero Brasil' },
  { src: '/images/wp/clients/almeida-carvalho.webp', alt: 'Almeida Carvalho' },
  { src: '/images/wp/clients/alphamec.webp', alt: 'Alphamec' },
  { src: '/images/wp/clients/anna-neg.webp', alt: 'Anna Neg' },
  { src: '/images/wp/clients/aquarium-store.webp', alt: 'Aquarium Store' },
  { src: '/images/wp/clients/arrumma.webp', alt: 'Arrumma' },
  { src: '/images/wp/clients/bauforte.webp', alt: 'Bauforte' },
  { src: '/images/wp/clients/belas-imagens.webp', alt: 'Belas Imagens' },
  { src: '/images/wp/clients/boteco-sao-rafael.webp', alt: 'Boteco São Rafael' },
  { src: '/images/wp/clients/bravo.webp', alt: 'Bravo' },
  { src: '/images/wp/clients/casa-nostra.webp', alt: 'Casa Nostra' },
  { src: '/images/wp/clients/cia-truck.webp', alt: 'Cia Truck' },
  { src: '/images/wp/clients/closet-31.webp', alt: 'Closet 31' },
  { src: '/images/wp/clients/comcam.webp', alt: 'COMCAM' },
  { src: '/images/wp/clients/comercio-online.webp', alt: 'Comércio Online' },
  { src: '/images/wp/clients/comissao-oab-mogi.webp', alt: 'Comissão OAB Mogi' },
  { src: '/images/wp/clients/consulting.webp', alt: 'Consulting' },
  { src: '/images/wp/clients/contraste.webp', alt: 'Contraste' },
  { src: '/images/wp/clients/corum.webp', alt: 'Corum' },
  { src: '/images/wp/clients/dobassi.webp', alt: 'Dobassi' },
  { src: '/images/wp/clients/dra-vanuza.webp', alt: 'Dra. Vanuza' },
  { src: '/images/wp/clients/easyfin.webp', alt: 'EasyFin' },
  { src: '/images/wp/clients/eco-maquinas.webp', alt: 'Eco Máquinas' },
  { src: '/images/wp/clients/eduarda-demazzi.webp', alt: 'Eduarda Demazzi' },
  { src: '/images/wp/clients/emporio-brauna.webp', alt: 'Empório Braúna' },
  { src: '/images/wp/clients/envolt.webp', alt: 'Envolt' },
  { src: '/images/wp/clients/fm-autoescola.webp', alt: 'FM Autoescola' },
  { src: '/images/wp/clients/formula-tatuador-pro.webp', alt: 'Fórmula Tatuador Pro' },
  { src: '/images/wp/clients/gaya.webp', alt: 'Gaya' },
  { src: '/images/wp/clients/gi-flores.webp', alt: 'Gi Flores' },
  { src: '/images/wp/clients/grupo-thermoprint.webp', alt: 'Grupo Thermoprint' },
  { src: '/images/wp/clients/injecar.webp', alt: 'Injecar' },
  { src: '/images/wp/clients/katia-fonseca.webp', alt: 'Kátia Fonseca' },
  { src: '/images/wp/clients/la-capanna.webp', alt: 'La Capanna' },
  { src: '/images/wp/clients/le-petrin.webp', alt: 'Le Pétrin' },
  { src: '/images/wp/clients/lm-assets.webp', alt: 'LM Assets' },
  { src: '/images/wp/clients/maciel-novaes.webp', alt: 'Maciel Novaes' },
  { src: '/images/wp/clients/madu.webp', alt: 'Madu' },
  { src: '/images/wp/clients/manuelitha.webp', alt: 'Manuelitha' },
  { src: '/images/wp/clients/mara-rocha.webp', alt: 'Mara Rocha' },
  { src: '/images/wp/clients/miliveste.webp', alt: 'Miliveste' },
  { src: '/images/wp/clients/motel-athos.webp', alt: 'Motel Athos' },
  { src: '/images/wp/clients/movfrete.webp', alt: 'MovFrete' },
  { src: '/images/wp/clients/ncf-seguros.webp', alt: 'NCF Seguros' },
  { src: '/images/wp/clients/newcia.webp', alt: 'NewCia' },
  { src: '/images/wp/clients/novo-suporte.webp', alt: 'Novo Suporte' },
  { src: '/images/wp/clients/ottimi.webp', alt: 'Ottimi' },
  { src: '/images/wp/clients/pet-company.webp', alt: 'Pet Company' },
  { src: '/images/wp/clients/pin-ideias.webp', alt: 'Pin Ideias' },
  { src: '/images/wp/clients/r2m.webp', alt: 'R2M' },
  { src: '/images/wp/clients/rm3.webp', alt: 'RM3' },
  { src: '/images/wp/clients/rovinglass.webp', alt: 'RovinGlass' },
  { src: '/images/wp/clients/sandre.webp', alt: 'Sandre' },
  { src: '/images/wp/clients/sartori-go.webp', alt: 'Sartori Go' },
  { src: '/images/wp/clients/talent.webp', alt: 'Talent' },
  { src: '/images/wp/clients/tatuadamente.webp', alt: 'Tatuadamente' },
  { src: '/images/wp/clients/tomperos.webp', alt: 'Tomperos' },
  { src: '/images/wp/clients/tplog.webp', alt: 'TPLog' },
  { src: '/images/wp/clients/vanguard.webp', alt: 'Vanguard' },
  { src: '/images/wp/clients/vcenario.webp', alt: 'Vcenario' },
  { src: '/images/wp/clients/veste-sky.webp', alt: 'Veste Sky' },
  { src: '/images/wp/clients/vieira.webp', alt: 'Vieira' },
] as const
